### ISSUE TITLE
HandlebarsFilter does not work

### ISSUE THREAD

**Issue by iricketson** [jasonlewis/basset#106]
Using Basset 4

My collection states:

``` php

$collection->requireDirectory('backbone/apps/footer/show/templates')->apply('Handlebars');

```

My Handlebars alias defines:

``` php

'Handlebars' => array('HandlebarsFilter', function($filter)
{
    $filter->whenAssetIs('*.handlebars')->findMissingConstructorArgs();
})

```

For some reason the handlebars files seem to be ignored.

**Comment by jasonlewis** [comment]
This is probably because Basset couldn't find the constructor arguments.
Take a look at the filter in the Assetic vendor directory and see what it
requires. You can then use setArguments() to set them manually.

**Comment by jasonlewis** [comment]
@iricketson I'm going to close this for now. I'll be implementing some form of logging soon since a lot of the time Basset just fails silently since sometimes this is preferred over killing the entire application. If files are being ignored the best thing to do is ensure that the Handlebars dependencies are being injected into the constructor. You can do this manually as I've said above.

**Comment by iricketson** [comment]
Sounds good Jason.  Thanks for the update.
