### ISSUE TITLE
Basset's assets stay uncompressed/uncached

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#36]
I'm using YSlow and Google Pagespeed to usually measure how I'm doing speed-wise. As I'm using the HTML5 Boilerpate's htaccess to provide Expire Headers, GZip compression and such, my assets are usually not a problem.
But here with Basset, it seems that no matter what I do, all the files that come from Basset are untouched by the htaccess – they refused to be cached, to be compressed or anything, which forces them to reload every pageload (which is quite a problem).

I don't know if this is a headers() problem or something; I used to use the famous [Minify](http://code.google.com/p/minify/) for assets concatenating/compressing etc, if really that's a headers problem maybe you could take a look at how it handled assets – they were always served gziped, minified and ready to cache.

(Note that you could also take a look at the libs it used to compressed assets, I think it might help)

**Comment by jasonlewis** [comment]
I'm actually finding this really hard to test. I've tested with many checkers, including YSlow and Google Pagespeed. I've also used some online tools to check. Some report it's being gzipped and others are not. I'm making some changes which I'll push to develop shortly that you can check if you have the time.

---

Try using the develop branch now. You _may_ be able to get away with just replacing the `start.php` file but I can't say for sure.

**Comment by Anahkiasen** [comment]
Well I was using the develop branch but then I had a bug and the fix was pushed to master instead so I switched to it. Will retest as soon as my holidays end.

**Comment by jasonlewis** [comment]
Okay sounds good, I'm going to do more testing for this tonight when I get the time. Hopefully have a release pushed out before I head back out to the island and am without the interwebs for 9 days.

**Comment by jasonlewis** [comment]
I honestly don't know what's going on @Anahkiasen. I've been trying for a while now to get _anything_ Gzipped but to no avail. PageSpeed and YSlow always told me it wasn't compressed, however other online tootls such as [GIDZipTest](http://www.gidnetwork.com/tools/gzip-test.php) all reported that things were being compressed successfully.

I've undone some of the changes I made because I was getting a lot of unexpected results locally, such as contents being cut-off halfway through rendering because of the content length. I'm not really sure what was happening. Was bizarre.

Unfortunately I don't want to merge the current develop with the master yet so things are going to have to stay on develop for at least the next 9 days while I head back out to the island for work. If you come across anything or anyway to solve it let me know!

I'll get back to this when I'm back. Thanks again.

**Comment by Anahkiasen** [comment]
Well I don't know what changes you made, did you take a look at Minify Gzip handler ? I think it's somewhere in [this file](https://github.com/mrclay/minify/blob/master/min/lib/HTTP/Encoder.php) or something. Anyway maybe it's just YSlow/PageSpeed detector's that report a false negative. Don't worry anyway it's not a pressing matter to me personally so I got all my time. When I get back from holidays I'll try to see what I can help with.

**Comment by kloy** [comment]
This appears to be due to no-cache being set in headers.

**Comment by kloy** [comment]
The easiest fix for this I can think of is to allow for production assets to be compiled to a directory and return a url for that directory. This would allow for the web server to handle the response instead of the Basset route.

**Comment by jasonlewis** [comment]
That's probably not a bad idea Keith. It would actually simplify a lot of
things related to Basset. I'll keep that in mind.

**Comment by jasonlewis** [comment]
This will be done in the next release.
