### ISSUE TITLE
Laravel 3 support

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#52]
I see the Laravel 4 branch was directly merged into master, what happens for Laravel 3 now ? On the docs it says Laravel 4 is required, what happens to all the people that hit `artisan bundle:update` and that now get an unworking version ?
People that use git submodules can still revert or not update but still,  that seems like a weird decision.

**Comment by jasonlewis** [comment]
Sorry, it wasn't one I made lightly. I'm not abandoning the L3 version entirely. For now I've moved it to an L3 branch. I plan on overhauling it so it works much the same as the L4 version.

I haven't paid nearly enough attention to this as I should have. I'll be going through the pull requests in due time but for now the L3 version is on the L3 branch. Obviously this means that you can't install or update via artisan with L3.

I do apologize for this. Please let me know what you think of how it works in L4 though. I've simplified it a lot. It started to get a bit out of hand on what it can and should do. Basset is now all about just managing your assets. None of that extra fancy stuff. Some might not agree with this decision, so remember you're welcome to fork and do what you like with Basset.

**Comment by Anahkiasen** [comment]
I took a look at the doc and it all seems good to me, loving the new build/compress to static assets and the CLI, those are two long awaited and amazing adds. I've had a little trouble accessing to my assets in development environment on my local L4 setup, for some reasons the default path to assets is app/assets/ but when you do a Basset::show() in development in tries to display assets that are in public/assets/ – don't know if that's how it's supposed to be or if it's a typo in the config file.

**Comment by jasonlewis** [comment]
Oops, you just found a bug. Cheers. Just patched it.

But yes, that's how it should work. In development Basset will allow you to route to your assets no matter where they are stored. Hopefully it's all working now. =)

**Comment by Anahkiasen** [comment]
I also have a hard time figuring out what filters really are – if I really got what's quickly said in the docs, those cover all previous assets processing functions such as minification, LESS/SASS/Coffee and such ? But how does one proceed ? I need to add like the Yii Compressor quoted as example to my Composer file or ?

Other than that as I said it all seems incredibly clean. I regret this didn't make it into the core of Laravel but with the ease Composer brought it's not has much of a problem than on L3. Excellent job.

**Comment by jasonlewis** [comment]
I'll eventually write some more detailed guides on using some of the filters. When you install Basset with Composer it installs Assetic, you may have noticed that Assetic suggests you also install some other packages such as [leafo/lessphp](https://packagist.org/packages/leafo/lessphp) and [leafo/scssphp](https://packagist.org/packages/leafo/scssphp). You can also check out the other filters on the [Assetic documentation](https://github.com/kriswallsmith/assetic/blob/master/docs/en/concepts.md#what-is-a-filter).

The **Yui** compressor can be grabbed from the [GitHub repository](https://github.com/yui/yuicompressor) (it's in the build folder). Remember you need Java installed. On Windows you might need to adjust the options so that Assetic can find it.

```
'filters' => array(
    'YuiCss' => array(
        'Yui\CssCompressor' => array('C:\Development\Basset\app\yuicompressor.jar', 'C:\Program Files (x86)\Java\jre7\bin\java.exe')
    )
)
```

The `Assetic\Filters\Yui\CssCompressorFilter` class extends `Assetic\Filters\Yui\BaseCompressorFilter` class, and [in that class](https://github.com/kriswallsmith/assetic/blob/master/src/Assetic/Filter/Yui/BaseCompressorFilter.php) the constructor accepts to parameters, the path to the .jar file and the path to java itself. So the options I've defined for this filter are the same, the first is the path to my .jar file and the second the path to java. This filter can now be applied by using the name `YuiCss`.

Hope that helps @Anahkiasen!
