### ISSUE TITLE
Problem with URI rewriter

### ISSUE THREAD

**Issue by Anahkiasen** [jasonlewis/basset#66]
I'm having trouble making the URI rewriter filters working. My assets are in `public/app`, so the references to images go like this : `../img/[myimage]`. When Basset compiles, I can't seem to make it rewrite the correct url to `../app/img/`.

``` php
Basset::collection('application', function($collection) {
  $collection->add('components/normalize/normalize.css');
  $collection->add('app/css/styles.css')->apply('UriRewriteFilter', array('public/app/'));

  $collection->add('app/js/scripts.js');
});
```

I've tried with `path('public').'app'` too, didn't work, same thing with Assetic's URI filter. I'm not sure the filter is event run because I placed an exit in the middle of the constructor and Basset compiled like there was no tomorrow.

**Comment by jasonlewis** [comment]
You need to use the path to your public directory, so path('public') should
be fine.

**Comment by Anahkiasen** [comment]
Nope, tried with both `path('public')` and `path('public').'app'`, all paths still point to `public/img`.

**Comment by Anahkiasen** [comment]
Ok after some poking around the problem doesn't stem from the filters themselves but from `Asset->compile()` not finding the filter itself on line 211. It does a check for two namespaces : Assetic's and Basset's and all my filters fail both tests. I'll keep poking see if I can find why.

``` php
$name = 'UriRewriteFilter';
var_dump(class_exists("Basset\\Filter\\{$name}")); // false
```

---

EDIT : Ok this was really dumb : the namespace is `Filter`, but the folder is named `filters` in Basset. 
Renamed it, now the class is found. Still not working but you know, at least it finds the filter.

---

OK it actually rewrites the CSS now. Path is still incorrect though, as the generated paths are somehow absolute instead of relatives, it looks for images in `/app/img/`. And since I'm in a subfolder it fucks everything up.
I figured it was the windows path that tricked it, so I tried with the server path (`http://127.0.0.1/mysite/` instead of `E:\Dropbox\etc...`) and for some reason it now looks for images in `blic/app/img`. Yup. `blic`. It think there's a rogue `substr` somewhere but where, now that's something else.

---

Ok so the felon is that line in UriRewriteFilter : `$path = substr($path, strlen($this->documentRoot));`. As it removes the number of characters from the windows path in the server path. So I think I'm supposed to use the windows path. Still don't get why the path is not complete though.

---

Well in the meantime I did this : `return '..'.$uri;` at the end of `rewriteRelative`. Which is a pretty horrible trick but I can't decide on whether it's a bug from Basset not getting that the compiled assets go in `public/assets` and not `public`, or whether that's a bug from me because I'm in a subfolder of my `127.0.0.1`. If `UriRwriteFilter` is based on Minify's I know I had problems back when I was using it because I was always in a subfolder on local and sometimes on production.

**Comment by Anahkiasen** [comment]
Nothing on this yet ?

**Comment by jasonlewis** [comment]
I'll take a look at this when I begin re-work on filters. Cheers @Anahkiasen.

**Comment by barryvdh** [comment]
I also had a problem with the UriRewriteFilter and a subfolder (127.0.0.1/myproject). Fixed it by changing the return on line 200 to `return \URL::asset( ltrim($uri, '/') );` 
This strips the first / and then passes it to the Laravel asset rewriter, which makes it an absolute link (127.0.0.1/myproject/img/asset.jpg, of myproject.com/img/asset.jpg). 
(But offcourse this only works because I'm dynamically generating the assets, instead of via artisan)

**Comment by barryvdh** [comment]
@Anahkiasen do you still have this problem?
In the latest develop branch, I use something like this:
   ->apply('UriRewriteFilter')->setArguments(public_path())
    ->apply('UriPrependFilter')->onEnvironment('local')->setArguments('/mysite')

This rewrites the paths correct, and adds a prefix on my local environment (because absolute links don't work otherwise) (And the UriPrependFilter is this: https://github.com/Barryvdh/assetic-filters/blob/master/src/UriPrependFilter.php, based on the UriRewriteFilter)

**Comment by jasonlewis** [comment]
I'm sure there's something else missing though. I'm home tonight so I'll
let you know.

**Comment by jasonlewis** [comment]
@Barryvdh Have you tried using the document root instead of the full path to the public directory?

Let's say you have the following directory structure:

```
/home
    /<user>
        /public_html
            /project
                /public
                    /css
                        /template.css
                    /img
                        /background.png
```

Now assume `template.css` has the following contents.

``` css
body {
    background-image: url('../img/background.png');
}
```

And your collection:

``` php
$app['basset']->collection('website', function($collection)
{
    $collection->add('css/template.css');
});
```

If you navigated to `localhost/project/public` you wouldn't see a background image. So apply the filter and set the document root to the document root.

``` php
$app['basset']->collection('website', function($collection)
{
    $collection->add('css/template.css')->apply('UriRewriteFilter')->setArguments('/home/<user>/public_html');
});
```

Now the background image should be displayed correctly.

I think at some point I was saying point it to the public directory? That might be true if you're application is residing in the root of `public_html`, but for sub directory apps you should still point it to the document root.

Let me know if that fixes anything. Also the `master` branch has a bugged version of the `UriRewriteFilter` so the above has been tested on the `develop` branch.

**Comment by jasonlewis** [comment]
What's the verdict @barryvdh. I'm still thinking this is working as expected... Can't be sure until someone else gives this a whirl though. :smile:

**Comment by barryvdh** [comment]
Ok, just tested with the setup you suggested and that works. The files get rewritten to /myproject/public/img/test.png
(I don't have to set an argument)

The problem probably was with my symlinks (in combination with the public_path())
I tried my original setup:

```
->apply('UriRewriteFilter')->setArguments(null, array('/var/www/html/myproject' => '/home/projects/myproject/public'))
```

And this now also works :)
