### ISSUE TITLE
[Issue] Problem with commands

### ISSUE THREAD

**Issue by brayann** [jasonlewis/basset#74]
Hi Jason, I'm not sure if I'm doing something wrong, but after I put the following code to app/start/global.php : 

Basset::collection('bootstrap', function($collection) {
    $collection->requireDirectory('path: bootstrap');
});

It's working fine on the browser (loading my assets), but when I do any command, i.e. a migration, I'm getting this error:

UnexpectedValueException</abbr>: FilesystemIterator::__construct(bootstrap): failed to open dir: No such file or directory

Let me know if u need more info.

And thanks, besides this, it's working great for me :+1:

**Comment by brayann** [comment]
<ol class="traces list_exception">
       <li> in /Applications/MAMP/htdocs/project/vendor/jasonlewis/basset/src/Basset/Directory.php line 70</li>
       <li>at <abbr title="FilesystemIterator">FilesystemIterator</abbr>->__construct('bootstrap') in /Applications/MAMP/htdocs/project/vendor/jasonlewis/basset/src/Basset/Directory.php line 70</li>
       <li>at <abbr title="Basset\Directory">Directory</abbr>->iterateDirectory() in /Applications/MAMP/htdocs/project/vendor/jasonlewis/basset/src/Basset/Directory.php line 106</li>
       <li>at <abbr title="Basset\Directory">Directory</abbr>->requireDirectory() in /Applications/MAMP/htdocs/project/vendor/jasonlewis/basset/src/Basset/Collection.php line 191</li>
       <li>at <abbr title="Basset\Collection">Collection</abbr>->requireDirectory('path: bootstrap') in /Applications/MAMP/htdocs/project/app/start/global.php line 40</li>
       <li>at <abbr title=""></abbr>{closure}(<em>object</em>(<abbr title="Basset\Collection">Collection</abbr>)) in /Applications/MAMP/htdocs/project/vendor/jasonlewis/basset/src/Basset/Basset.php line 94</li>
       <li>at <abbr title="Basset\Basset">Basset</abbr>->collection('bootstrap', <em>object</em>(<abbr title="Closure">Closure</abbr>)) in /Applications/MAMP/htdocs/project/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php line 108</li>
       <li>at <abbr title="Illuminate\Support\Facades\Facade">Facade</abbr>::__callStatic('collection', <em>array</em>('bootstrap', <em>object</em>(<abbr title="Closure">Closure</abbr>))) in /Applications/MAMP/htdocs/project/app/start/global.php line 41</li>
       <li>at <abbr title="Basset\Facades\Basset">Basset</abbr>::collection('bootstrap', <em>object</em>(<abbr title="Closure">Closure</abbr>)) in /Applications/MAMP/htdocs/project/app/start/global.php line 41</li>
       <li>at <abbr title=""></abbr>require('/Applications/MAMP/htdocs/project/app/start/global.php') in /Applications/MAMP/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/start.php line 199</li>
       <li>at <abbr title=""></abbr>require('/Applications/MAMP/htdocs/project/vendor/laravel/framework/src/Illuminate/Foundation/start.php') in /Applications/MAMP/htdocs/project/start.php line 60</li>
       <li>at <abbr title=""></abbr>require_once('/Applications/MAMP/htdocs/project/start.php') in /Applications/MAMP/htdocs/project/artisan line 46</li>
    </ol>

**Comment by ghost** [comment]
I'm getting a similar pathing problem - here's my Basset setup in app/start/global.php:

![Basset config](https://f.cloud.github.com/assets/3375290/95929/7ee00ec8-6684-11e2-8673-affce731f448.png)

The collection works fine on my web app, but if I run:

```
php artisan
```

I get this:

![Error Message from Artisan CLI](https://f.cloud.github.com/assets/3375290/95917/3ed94ab0-6684-11e2-90af-482348a3fba2.png)

Here's my layout:

![Public folder](https://f.cloud.github.com/assets/3375290/95915/22b8f6d2-6684-11e2-957b-ccd8c01352c0.png)

I'm using the latest beta of Laravel 4 and I've done a full composer update. I'm guessing it's something to do with environments and paths, but I don't see why Artisan doesn't use the same paths as the app.

Thanks!

**Comment by Anahkiasen** [comment]
Don't use `path:`. Basset looks in public by default.

**Comment by ghost** [comment]
Thanks for the reply @Anahkiasen. I have tried a few different configurations based on the Basset 4 documentation. 

Here's what I've changed my Basset collection to based on your advice:

![basset](https://f.cloud.github.com/assets/3375290/95975/e220c6a0-6687-11e2-92ae-3ca9f94e24ea.png)

I'm still getting this error though:

![error](https://f.cloud.github.com/assets/3375290/95972/d5627530-6687-11e2-8605-3d59c93e0831.png)

Interestingly both the app and Artisan work if I hardcode the URL for the asset like this:

![basset_full_url](https://f.cloud.github.com/assets/3375290/95989/b45be1e0-6688-11e2-8855-1ed924ba35de.png)

I'm pretty new to Laravel, and I've made the decision to start with version 4 - I know version 3 is stable, but I figure if I'm going to learn the framework effectively, I may as well start with the latest version and hopefully powering through issues like this will mean I'm more proficient in the future.

Thanks for your time!

<b>Edit:</b>

Here's the $assetPath being resolved in vendor\jasonlewis\basset\src\Basset\Collection.php:

![assetpath](https://f.cloud.github.com/assets/3375290/96071/fdf99e50-668d-11e2-9c4a-5bdde95a7e68.png)

Since the collection is being echoed to a head section in a view, I don't know why it's not a URI being resolved. I could understand if the collection was to be included in a script, obviously then you'd need the path, but in this case I really need the base URL + the added asset path.

**Comment by jasonlewis** [comment]
Exceptions are handled much better by Basset in the upcoming unreleased version. I'm going to close this for now. Once the newest develop branch hits and you're still getting problems hit up this issue and I'll re-open.

Cheers.
